# Generated by Django 3.2 on 2021-05-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classid', models.AutoField(db_column='ClassID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('noofstudent', models.IntegerField(blank=True, db_column='NoOfStudent', null=True)),
            ],
            options={
                'db_table': 'Class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('change_message', models.TextField()),
                ('action_flag', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionid', models.AutoField(db_column='QuestionID', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
                ('modelans', models.CharField(blank=True, db_column='ModelAns', max_length=255, null=True)),
                ('question', models.CharField(blank=True, db_column='Question', max_length=255, null=True)),
                ('activestatus', models.SmallIntegerField(blank=True, db_column='ActiveStatus', null=True)),
                ('partstatus', models.SmallIntegerField(blank=True, db_column='PartStatus', null=True)),
                ('questtotalmark', models.TextField(blank=True, db_column='QuestTotalMark', null=True)),
                ('archivedby', models.CharField(blank=True, db_column='ArchivedBy', max_length=255, null=True)),
                ('updatedby', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('addedby', models.CharField(blank=True, db_column='AddedBy', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partid', models.CharField(db_column='PartID', max_length=255)),
                ('partquestion', models.CharField(blank=True, db_column='PartQuestion', max_length=255, null=True)),
                ('partmodelans', models.CharField(blank=True, db_column='PartModelAns', max_length=255, null=True)),
                ('parttotalmark', models.TextField(blank=True, db_column='PartTotalMark', null=True)),
            ],
            options={
                'db_table': 'QuestionPart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studid', models.AutoField(db_column='StudID', primary_key=True, serialize=False)),
                ('classid', models.IntegerField(db_column='ClassID')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('nric', models.TextField(blank=True, db_column='NRIC', null=True)),
            ],
            options={
                'db_table': 'Student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrnQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, db_column='Response', max_length=255, null=True)),
                ('trnmark', models.CharField(blank=True, db_column='TrnMark', max_length=255, null=True)),
                ('reason', models.CharField(blank=True, db_column='Reason', max_length=255, null=True)),
                ('other', models.CharField(blank=True, db_column='Other', max_length=255, null=True)),
                ('moderatedby', models.DateField(blank=True, db_column='ModeratedBy', null=True)),
                ('datemoderated', models.DateField(blank=True, db_column='DateModerated', null=True)),
                ('datemarked', models.DateField(blank=True, db_column='DateMarked', null=True)),
            ],
            options={
                'db_table': 'TrnQuest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrnQuestPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionid', models.IntegerField(db_column='QuestionID')),
                ('partid', models.CharField(db_column='PartID', max_length=255)),
                ('partresponse', models.CharField(blank=True, db_column='PARTRESPONSE', max_length=255, null=True)),
                ('other', models.CharField(blank=True, db_column='Other', max_length=255, null=True)),
                ('moderatedby', models.DateField(blank=True, db_column='ModeratedBy', null=True)),
                ('datemoderated', models.DateField(blank=True, db_column='DateModerated', null=True)),
                ('datemarked', models.DateField(blank=True, db_column='DateMarked', null=True)),
                ('reason', models.CharField(blank=True, db_column='Reason', max_length=255, null=True)),
            ],
            options={
                'db_table': 'TrnQuestPart',
                'managed': False,
            },
        ),
    ]
