# Generated by Django 3.2 on 2021-04-14 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.BigIntegerField(db_column='QuestionID', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='Description', max_length=256)),
                ('model_ans', models.CharField(db_column='ModelAns', max_length=256)),
                ('active_status', models.CharField(db_column='ActiveStatus', max_length=64)),
                ('part_status', models.CharField(db_column='PartStatus', max_length=64)),
                ('quest_total_mark', models.FloatField(db_column='QuestTotalMark')),
                ('updated_by', models.CharField(db_column='UpdatedBy', max_length=256)),
                ('archived_by', models.CharField(db_column='ArchivedBy', max_length=256)),
                ('added_by', models.CharField(db_column='AddedBy', max_length=256)),
                ('question', models.CharField(db_column='Question', max_length=256)),
            ],
            options={
                'db_table': 'Question',
            },
        ),
        migrations.CreateModel(
            name='QuestionPart',
            fields=[
                ('part_id', models.BigIntegerField(db_column='PartID', primary_key=True, serialize=False)),
                ('part_desc', models.CharField(db_column='PartDesc', max_length=256)),
                ('part_model_ans', models.CharField(db_column='PartModelAns', max_length=256)),
                ('part_total_mark', models.FloatField(db_column='PartTotalMark')),
                ('question_id', models.ForeignKey(db_column='QuestionID', on_delete=django.db.models.deletion.CASCADE, to='api.question')),
            ],
            options={
                'db_table': 'QuestionPart',
                'managed': True,
                'unique_together': {('part_id', 'question_id')},
            },
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('trainee_id', models.BigIntegerField(db_column='TraineeID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=256)),
                ('nric', models.CharField(db_column='NRIC', max_length=256)),
                ('squad_id', models.CharField(db_column='SquadID', max_length=256)),
            ],
            options={
                'db_table': 'Trainee',
            },
        ),
        migrations.CreateModel(
            name='TrnQuestPart',
            fields=[
                ('trn_quest_part_id', models.BigIntegerField(db_column='TrnQuestPartID', primary_key=True, serialize=False)),
                ('part_response', models.CharField(db_column='PartResponse', max_length=256)),
                ('reason', models.CharField(db_column='Reason', max_length=256)),
                ('other', models.CharField(db_column='Other', max_length=256)),
                ('moderated_by', models.CharField(db_column='ModeratedBy', max_length=256)),
                ('date_moderated', models.DateField(db_column='DateModerated')),
                ('trn_part_mark', models.FloatField(db_column='TrnPartMark')),
                ('part_id', models.ForeignKey(db_column='PartID', on_delete=django.db.models.deletion.CASCADE, to='api.questionpart')),
                ('question_id', models.ForeignKey(db_column='QuestionID', on_delete=django.db.models.deletion.CASCADE, to='api.question')),
                ('trainee_id', models.ForeignKey(db_column='TraineeID', on_delete=django.db.models.deletion.CASCADE, to='api.trainee')),
            ],
            options={
                'db_table': 'TrnQuestPart',
                'managed': True,
                'unique_together': {('trainee_id', 'question_id', 'part_id')},
            },
        ),
        migrations.CreateModel(
            name='TrnQuest',
            fields=[
                ('trn_quest_id', models.BigIntegerField(db_column='TrnQuestID', primary_key=True, serialize=False)),
                ('response', models.CharField(db_column='Response', max_length=256)),
                ('trn_mark', models.FloatField(db_column='TrnMark')),
                ('reason', models.CharField(db_column='Reason', max_length=256)),
                ('other', models.CharField(db_column='Other', max_length=256)),
                ('moderated_by', models.CharField(db_column='ModeratedBy', max_length=256)),
                ('date_marked', models.DateField(db_column='DateMarked')),
                ('date_moderated', models.DateField(db_column='DateModerated')),
                ('question_id', models.ForeignKey(db_column='QuestionID', on_delete=django.db.models.deletion.CASCADE, to='api.question')),
                ('trainee_id', models.ForeignKey(db_column='TraineeID', on_delete=django.db.models.deletion.CASCADE, to='api.trainee')),
            ],
            options={
                'db_table': 'TrnQuest',
                'managed': True,
                'unique_together': {('trainee_id', 'question_id')},
            },
        ),
    ]
