# Generated by Django 3.2 on 2021-05-07 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.BigIntegerField(db_column='ClassID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=256)),
                ('no_of_student', models.IntegerField(db_column='NoOfStudent')),
            ],
            options={
                'db_table': 'Class',
            },
        ),
        migrations.RemoveField(
            model_name='questionpart',
            name='part_desc',
        ),
        migrations.AddField(
            model_name='questionpart',
            name='part_question',
            field=models.CharField(db_column='PartQuestion', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='trnquestpart',
            name='date_marked',
            field=models.DateField(auto_now=True, db_column='DateMarked'),
        ),
        migrations.AlterField(
            model_name='question',
            name='active_status',
            field=models.BooleanField(db_column='ActiveStatus', default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='added_by',
            field=models.CharField(db_column='AddedBy', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='archived_by',
            field=models.CharField(db_column='ArchivedBy', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='part_status',
            field=models.BooleanField(db_column='PartStatus', default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='quest_total_mark',
            field=models.FloatField(db_column='QuestTotalMark', default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(db_column='Question', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_by',
            field=models.CharField(db_column='UpdatedBy', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='questionpart',
            name='part_id',
            field=models.CharField(db_column='PartID', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questionpart',
            name='part_total_mark',
            field=models.FloatField(db_column='PartTotalMark', default=0),
        ),
        migrations.AlterField(
            model_name='questionpart',
            name='question_id',
            field=models.ForeignKey(db_column='QuestionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
        migrations.AlterField(
            model_name='trnquest',
            name='date_marked',
            field=models.DateField(auto_now=True, db_column='DateMarked'),
        ),
        migrations.AlterField(
            model_name='trnquest',
            name='date_moderated',
            field=models.DateField(db_column='DateModerated', null=True),
        ),
        migrations.AlterField(
            model_name='trnquest',
            name='moderated_by',
            field=models.CharField(db_column='ModeratedBy', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='trnquest',
            name='other',
            field=models.CharField(db_column='Other', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='trnquest',
            name='question_id',
            field=models.ForeignKey(db_column='QuestionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
        migrations.AlterField(
            model_name='trnquest',
            name='reason',
            field=models.CharField(db_column='Reason', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='trnquest',
            name='response',
            field=models.CharField(db_column='Response', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='trnquest',
            name='trn_mark',
            field=models.FloatField(db_column='TrnMark', null=True),
        ),
        migrations.AlterField(
            model_name='trnquestpart',
            name='date_moderated',
            field=models.DateField(db_column='DateModerated', null=True),
        ),
        migrations.AlterField(
            model_name='trnquestpart',
            name='moderated_by',
            field=models.CharField(db_column='ModeratedBy', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='trnquestpart',
            name='other',
            field=models.CharField(db_column='Other', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='trnquestpart',
            name='part_id',
            field=models.ForeignKey(db_column='PartID', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.questionpart'),
        ),
        migrations.AlterField(
            model_name='trnquestpart',
            name='question_id',
            field=models.ForeignKey(db_column='QuestionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
        migrations.AlterField(
            model_name='trnquestpart',
            name='reason',
            field=models.CharField(db_column='Reason', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='trnquestpart',
            name='trn_part_mark',
            field=models.FloatField(db_column='TrnPartMark', null=True),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.BigIntegerField(db_column='StudID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=256)),
                ('nric', models.CharField(db_column='NRIC', max_length=256, null=True)),
                ('class_id', models.ForeignKey(db_column='ClassID', on_delete=django.db.models.deletion.CASCADE, to='api.class')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.AddField(
            model_name='trnquest',
            name='student_id',
            field=models.ForeignKey(db_column='StudID', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.AddField(
            model_name='trnquestpart',
            name='student_id',
            field=models.ForeignKey(db_column='StudID', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.AlterUniqueTogether(
            name='trnquest',
            unique_together={('student_id', 'question_id')},
        ),
        migrations.AlterUniqueTogether(
            name='trnquestpart',
            unique_together={('student_id', 'question_id', 'part_id')},
        ),
        migrations.RemoveField(
            model_name='trnquest',
            name='trainee_id',
        ),
        migrations.RemoveField(
            model_name='trnquestpart',
            name='trainee_id',
        ),
        migrations.DeleteModel(
            name='Trainee',
        ),
    ]
