# Generated by Django 3.2 on 2021-05-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210507_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpart',
            name='question_part_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionpart',
            name='part_id',
            field=models.CharField(db_column='PartID', max_length=5),
        ),
    ]
